fotoblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin
from blog import views
import authentication.views
from authentication import views as auth_views
import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.login_page, name='login'),
    path('signup/', authentication.views.signup_page, name='signup'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('home/', blog.views.home, name='home'),
    path('photo/upload/', blog.views.upload_photo, name='upload_photo'),
    path('upload_profile_photo/', auth_views.upload_profile_photo, name='upload_profile_photo'),
    path('blog/<int:pk>/', blog.views.view_blog, name='view_blog'),
    path('profile/', auth_views.user_profile, name='user_profile'),
    path('create/', blog.views.blog_create, name='blog_create'),
    path('changer-photo/', auth_views.upload_profile_photo, name='upload_profile_photo'),
    path('blog/<int:blog_id>/edit/', blog.views.edit_blog, name='edit_blog'),
    path('photo/upload_multiple/', blog.views.create_multiple_photos, name='create_multiple_photos'),
    path('follow_users/', blog.views.follow_users, name='follow_users')



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from PIL import Image


class Photo(models.Model):
    image = models.ImageField(upload_to='photos/')
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
IMAGE_MAX_SIZE = (800, 800)
def resize_image(image):
    img = Image.open(image.path)
    img.thumbnail(IMAGE_MAX_SIZE)
    img.save(image.path)

def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()


class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    contributors = models.ManyToManyField(
settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')
    class Meta:
         permissions =[('change_blog_title', 'Can change blog title')]

 
class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)
    
    class Meta:
        unique_together = ('contributor', 'blog')   

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>FotoBlog</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="sidebar">
        <h1>FotoBlog</h1>

        {% if request.user.is_authenticated %}
            <p>Salut, {{ request.user.username }} !</p>

            
            <img src="{% static 'images/default-profile.jpg' %}" alt="profil">

            <nav>
                <a href="{% url 'home' %}">Accueil</a>
                {% if perms.blog.add_blog %}
                    <a href="{% url 'blog_create' %}">Écrire un billet</a>
                {% endif %}
                {% if perms.blog.add_photo %}
                    <a href="{% url 'upload_photo' %}">Téléverser une photo</a>
                    <a href="{% url 'create_multiple_photos' %}">Téléverser plusieurs photos</a>
                {% endif %}
                <a href="{% url 'user_profile' %}">Mon profil</a>
                <a href="{% url 'logout' %}">Se déconnecter</a>
            <p><a href="{% url 'follow_users' %}">Suivre des utilisateurs</a></p>
            <p><a href="{% url 'upload_profile_photo' %}">Changer la photo de profil</a></p>
            </nav>
        {% else %}
            <p><a href="{% url 'login' %}">Se connecter</a></p>
        {% endif %}
    </div>

    <div class="main-content">
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>